// <auto-generated />
namespace BorgCivil.Framework.Identity
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class changeInSite : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeInSite));
        
        string IMigrationMetadata.Id
        {
            get { return "201703231022068_changeInSite"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
