// <auto-generated />
namespace BorgCivil.Framework.Identity
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class anonymousField : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(anonymousField));
        
        string IMigrationMetadata.Id
        {
            get { return "201705030602016_anonymousField"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
