// <auto-generated />
namespace BorgCivil.Framework.Identity
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class DocketChanges1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DocketChanges1));
        
        string IMigrationMetadata.Id
        {
            get { return "201704111125035_DocketChanges1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
