//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TV.CraveASAP.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppDefaultLandingPage
    {
        public int landingPageId { get; set; }
        public string type { get; set; }
        public string fromTime { get; set; }
        public string toTime { get; set; }
        public int categoryId { get; set; }
        public string categoryStatus { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
