//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TV.CraveASAP.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Banner
    {
        public int bannerId { get; set; }
        public string type { get; set; }
        public string platform { get; set; }
        public string language { get; set; }
        public string imageURL { get; set; }
        public string reference { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public string delay { get; set; }
    }
}
