//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TV.CraveASAP.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContentManagement
    {
        public int id { get; set; }
        public string contentName { get; set; }
        public string contentLink { get; set; }
        public Nullable<bool> isActive { get; set; }
    }
}
