//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TV.CraveASAP.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DynamicHTMLContent
    {
        public int Id { get; set; }
        public string pageName { get; set; }
        public string language { get; set; }
        public string pageContent { get; set; }
        public string plainText { get; set; }
        public string contentFor { get; set; }
    }
}
