//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TV.CraveASAP.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public int locationId { get; set; }
        public string locationName { get; set; }
        public string city { get; set; }
        public string region { get; set; }
        public string address { get; set; }
    }
}
