//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TV.CraveASAP.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OAuth
    {
        public int oAuthId { get; set; }
        public Nullable<int> loginId { get; set; }
        public string appType { get; set; }
        public string OAuthToken { get; set; }
        public Nullable<System.DateTime> time { get; set; }
    }
}
