//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TV.CraveASAP.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OpeningHour
    {
        public int openingHoursId { get; set; }
        public string fromday { get; set; }
        public string today { get; set; }
        public string fromtime { get; set; }
        public string totime { get; set; }
        public int fkvendorId { get; set; }
    
        public virtual Vendor Vendor { get; set; }
    }
}
