//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TV.CraveASAP.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OptionalCategory
    {
        public int optCategoryId { get; set; }
        public string optCategoryName { get; set; }
        public string description { get; set; }
        public string language { get; set; }
        public int categoryId { get; set; }
        public int subCategoryId { get; set; }
        public Nullable<bool> isDeleted { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual SubCategory SubCategory { get; set; }
    }
}
