//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TV.CraveASAP.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PointsConfiguration
    {
        public int ptConfigurationId { get; set; }
        public string action { get; set; }
        public Nullable<int> limit { get; set; }
        public Nullable<int> pointsEarned { get; set; }
    }
}
