//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TV.CraveASAP.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PredictiveNotification
    {
        public int preId { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<int> promotionCodeId { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<System.DateTime> sendTime { get; set; }
        public string reSendTime { get; set; }
    }
}
