//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TV.CraveASAP.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reward
    {
        public Reward()
        {
            this.UserRewards = new HashSet<UserReward>();
        }
    
        public int rewardId { get; set; }
        public string rewardName { get; set; }
        public string description { get; set; }
        public string image { get; set; }
        public string platform { get; set; }
        public string code { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public string expiryHours { get; set; }
        public Nullable<bool> isSpecial { get; set; }
        public string nextAvailability { get; set; }
        public string type { get; set; }
        public Nullable<int> usedCount { get; set; }
        public Nullable<bool> isActive { get; set; }
        public string language { get; set; }
        public string link { get; set; }
        public string point { get; set; }
    
        public virtual ICollection<UserReward> UserRewards { get; set; }
    }
}
