//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TV.CraveASAP.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPromotion
    {
        public int userPromotionId { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<int> promotionId { get; set; }
        public Nullable<bool> isRecommended { get; set; }
        public Nullable<bool> isShareFacebook { get; set; }
        public Nullable<bool> isShareTwitter { get; set; }
        public Nullable<bool> isShareInstagram { get; set; }
        public Nullable<bool> isViewed { get; set; }
        public Nullable<bool> isUsed { get; set; }
        public string userTime { get; set; }
        public Nullable<System.DateTime> useDate { get; set; }
        public Nullable<bool> isDeleted { get; set; }
    
        public virtual PromotionCode PromotionCode { get; set; }
        public virtual User User { get; set; }
    }
}
