//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TV.CraveASAP.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLocation
    {
        public int userLocationId { get; set; }
        public int fkUser { get; set; }
        public Nullable<bool> isDefault { get; set; }
        public string mealTime { get; set; }
        public string locationAddress { get; set; }
        public string locationLat { get; set; }
        public string locationLong { get; set; }
        public Nullable<bool> isCurrent { get; set; }
        public Nullable<System.DateTime> visitedDatetime { get; set; }
        public Nullable<bool> isDeleted { get; set; }
    
        public virtual UserLocation UserLocations1 { get; set; }
        public virtual UserLocation UserLocation1 { get; set; }
    }
}
