//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TV.CraveASAP.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.UserFavourites = new HashSet<UserFavourite>();
            this.UserPrefrences = new HashSet<UserPrefrence>();
            this.UserPromotions = new HashSet<UserPromotion>();
            this.UserRewards = new HashSet<UserReward>();
        }
    
        public int userId { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string profilePicture { get; set; }
        public string gender { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<int> points { get; set; }
        public string facebookId { get; set; }
        public Nullable<System.DateTime> facebookInviteDate { get; set; }
        public Nullable<int> facebookInviteCount { get; set; }
        public Nullable<System.DateTime> instagramInviteDate { get; set; }
        public Nullable<int> instagramInviteCount { get; set; }
        public Nullable<System.DateTime> twitterInviteDate { get; set; }
        public Nullable<int> twitterInviteCount { get; set; }
        public Nullable<System.DateTime> dealFacebookInviteDate { get; set; }
        public Nullable<int> dealFacebookInviteCount { get; set; }
        public Nullable<System.DateTime> dealInstagramInviteDate { get; set; }
        public Nullable<int> dealInstagramInviteCount { get; set; }
        public Nullable<System.DateTime> dealTwitterInviteDate { get; set; }
        public Nullable<int> dealTwitterInviteCount { get; set; }
        public string language { get; set; }
        public string deviceToken { get; set; }
        public string devicePlatform { get; set; }
        public Nullable<System.DateTime> usePromoDate { get; set; }
        public Nullable<int> useCount { get; set; }
        public Nullable<System.DateTime> likePromoDate { get; set; }
        public Nullable<int> likeCount { get; set; }
    
        public virtual ICollection<UserFavourite> UserFavourites { get; set; }
        public virtual ICollection<UserPrefrence> UserPrefrences { get; set; }
        public virtual ICollection<UserPromotion> UserPromotions { get; set; }
        public virtual ICollection<UserReward> UserRewards { get; set; }
    }
}
