//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TV.CraveASAP.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorBranch
    {
        public int vendorBranchId { get; set; }
        public string businessName { get; set; }
        public string taxId { get; set; }
        public string location { get; set; }
        public string fullAddress { get; set; }
        public string deliveryAddress { get; set; }
        public string phoneNo { get; set; }
        public string contactPerson { get; set; }
        public string additionalInfo { get; set; }
        public string defaultBranch { get; set; }
        public string email { get; set; }
        public int vendorId { get; set; }
        public string branchCode { get; set; }
    
        public virtual Vendor Vendor { get; set; }
    }
}
